---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: helm-operator
  namespace: flux
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: helm-operator
  chart:
    repository: https://charts.fluxcd.io
    name: helm-operator
    version: 1.1.0
  values:
    git:
      ssh:
        secretName: flux-git-deploy
    helm:
      versions: v3
    image:
      repository: raspbernetes/helm-operator
      tag: v1.1.0
