---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: unifi
  namespace: unifi
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: unifi
  chart:
    git: https://github.com/RobReus/k8s-gitops
    name: charts/unifi
    ref: master
  values:
    image:
      repository: linuxserver/unifi-controller
      tag: 5.13.29-ls63
    guiService:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/address-pool: default
        metallb.universe.tf/allow-shared-ip: unifi
    controllerService:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/address-pool: default
        metallb.universe.tf/allow-shared-ip: unifi
    stunService:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/address-pool: default
        metallb.universe.tf/allow-shared-ip: unifi
    discoveryService:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/address-pool: default
        metallb.universe.tf/allow-shared-ip: unifi
    persistence:
      storageClass: openebs-sc-statefulset
