---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: traefik
  chart:
    repository: https://containous.github.io/traefik-helm-chart
    name: traefik
    version: 8.7.1
  values:
    additionalArguments:
      - "--certificatesresolvers.le.acme.storage=/data/acme.json"
    persistence:
      enabled: true
