---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: ingress-nginx
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 2.9.0
#  values:
#    controller:
#      config:
#        ssl-protocols: TLSv1.3 TLSv1.2
#        use-forwarded-headers: 'false'
