---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt
  namespace: home-automation
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: openebs-sc-statefulset
