---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: rob+letsencrypt@devrobs.nl
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - selector:
          dnsZones:
            - "rreus.nl"
            - "devrobs.nl"
        dns01:
          route53:
            region: eu-west-1
            accessKeyID: AKIASL54ODBRMD4N2AHL
            secretAccessKeySecretRef:
              name: route53-iam-key
              key: secret-access-key
